### ISSUE TITLE
"Exceeded Number of Random Initializations" in FirstTimeUse

### ISSUE THREAD

**Issue by WardLT** [Argonne-National-Laboratory/Frhodo#5]
I get a Runtime error when executing the "FirstTimeDemo." Is that expected? I do get rbfopt to function when I only provide a 1% bound on `k` for R3 in the example. Not when I follow the instructions as I understand them 

![image](https://user-images.githubusercontent.com/7003149/182180323-2372b0ce-a162-41db-822c-618675ecea60.png)

Full traceback

```
Traceback (most recent call last):
  File "D:\Users\wardl\Work\AutomatedLabs\Frhodo\src\calculate\optimize\optimize_worker.py", line 151, in run
    res = self.optimize_coeffs()
  File "D:\Users\wardl\Work\AutomatedLabs\Frhodo\src\calculate\optimize\optimize_worker.py", line 103, in optimize_coeffs
    res = optimize.run()
  File "D:\Users\wardl\Work\AutomatedLabs\Frhodo\src\calculate\optimize\optimize_worker.py", line 251, in run
    res[opt_type] = self.rbfopt(x0, bnds, options)
  File "D:\Users\wardl\Work\AutomatedLabs\Frhodo\src\calculate\optimize\optimize_worker.py", line 400, in rbfopt
    val, x, itercount, evalcount, fast_evalcount = algo.optimize()
  File "C:\Users\wardl\miniconda3\envs\frhodo\lib\site-packages\rbfopt\rbfopt_algorithm.py", line 803, in optimize
    self.optimize_serial(pause_after_iters)
  File "C:\Users\wardl\miniconda3\envs\frhodo\lib\site-packages\rbfopt\rbfopt_algorithm.py", line 857, in optimize_serial
    self.restart()
  File "C:\Users\wardl\miniconda3\envs\frhodo\lib\site-packages\rbfopt\rbfopt_algorithm.py", line 1813, in restart
    node_pos = ru.initialize_nodes(
  File "C:\Users\wardl\miniconda3\envs\frhodo\lib\site-packages\rbfopt\rbfopt_utils.py", line 565, in initialize_nodes
    raise RuntimeError('Exceeded number of random initializations')
RuntimeError: Exceeded number of random initializations
```

**Comment by RobertTranter** [comment]
Logan,
I am back from vacation. There are certainly a number of bugs in Frhodo. I seem to find ones on a regular basis. Are you able to run Frhodo? I can provide examples of data files I have worked on recently if that would help.
Regards
Rob
From: Logan Ward ***@***.***>
Sent: Monday, August 1, 2022 10:06 AM
To: Argonne-National-Laboratory/Frhodo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Argonne-National-Laboratory/Frhodo] "Exceeded Number of Random Initializations" in FirstTimeUse (Issue #5)


I get a Runtime error when executing the "FirstTimeDemo." Is that expected? I do get rbfopt to function when I only provide a 1% bound on k for R3 in the example. Not when I follow the instructions as I understand them

[Image removed by sender. image]<https://user-images.githubusercontent.com/7003149/182180323-2372b0ce-a162-41db-822c-618675ecea60.png>

Full traceback

Traceback (most recent call last):

  File "D:\Users\wardl\Work\AutomatedLabs\Frhodo\src\calculate\optimize\optimize_worker.py", line 151, in run

    res = self.optimize_coeffs()

  File "D:\Users\wardl\Work\AutomatedLabs\Frhodo\src\calculate\optimize\optimize_worker.py", line 103, in optimize_coeffs

    res = optimize.run()

  File "D:\Users\wardl\Work\AutomatedLabs\Frhodo\src\calculate\optimize\optimize_worker.py", line 251, in run

    res[opt_type] = self.rbfopt(x0, bnds, options)

  File "D:\Users\wardl\Work\AutomatedLabs\Frhodo\src\calculate\optimize\optimize_worker.py", line 400, in rbfopt

    val, x, itercount, evalcount, fast_evalcount = algo.optimize()

  File "C:\Users\wardl\miniconda3\envs\frhodo\lib\site-packages\rbfopt\rbfopt_algorithm.py", line 803, in optimize

    self.optimize_serial(pause_after_iters)

  File "C:\Users\wardl\miniconda3\envs\frhodo\lib\site-packages\rbfopt\rbfopt_algorithm.py", line 857, in optimize_serial

    self.restart()

  File "C:\Users\wardl\miniconda3\envs\frhodo\lib\site-packages\rbfopt\rbfopt_algorithm.py", line 1813, in restart

    node_pos = ru.initialize_nodes(

  File "C:\Users\wardl\miniconda3\envs\frhodo\lib\site-packages\rbfopt\rbfopt_utils.py", line 565, in initialize_nodes

    raise RuntimeError('Exceeded number of random initializations')

RuntimeError: Exceeded number of random initializations

**Comment by WardLT** [comment]
Hey Rob! No problem for the delay, I've been able to make notable progress on running Frhodo. 

I'm currently scrambling before I travel (to Argonne!), and will update you on that soon.

**Comment by WardLT** [comment]
Wrt to this issue. I can get Frhodo to run if I optimize different parameters than those listed in the tutorial document.

**Comment by RobertTranter** [comment]
Logan,
Thanks for the update. I will take a look at the tutorial later this week.
Rob
